### ISSUE TITLE
On MacOs / Safari : deleting a resource from a dataset doesn't close the `delete` modal

### ISSUE THREAD

**Issue by JulienParis** [opendatateam/udata#2509] opened 2020-06-25 13:40 UTC
important : **using Safari on a Mac**, following those steps we got a weird behaviour: 

- open a dataset you got admin rights upon and containing resources... for instance open it on the public part of the website ;
- click on `modify it` ;
- you are redirected to the admin part of the website ;
- click on a resource you want to delete ;
- click on `delete this resource`, you got this page ; 
![Capture d’écran 2020-06-25 à 15 22 27](https://user-images.githubusercontent.com/21986727/85728496-4391e180-b6f8-11ea-84a1-ebacedc4f9c9.png)

- click on `confim` 

=> the modal doesn't disappear, but it seems the resource is correctly deleted from the dataset (but you'll see that only if you relaod the page)... 

=> expected behaviour : 

- even on Safari, when you want to delete a resource from a dataset, the red delete modal should disappear when once you have clicked on "confirm", and the resource should be deleted from the resources list

## Your Environment
* Browser Name and version: Safari 13.1.1 (15609.2.9.1.2)
* Operating System and version (desktop or mobile): Desktop - MacOS 10.15.5 Catalina

**Comment by abulte** [comment] 2020-06-25 13:42
Duplicate of https://github.com/opendatateam/udata/issues/1773

Please search for issues before creating new ones. Can do this for all your recent issues? I knew about all of them so they might very already exist somewhere. Include https://github.com/etalab/data.gouv.fr in your search.

**Closed by abulte** 2020-06-25 13:42 UTC
Labels: bug

**Comment by JulienParis** [comment] 2020-06-25 14:09
> Duplicate of #1773
> 
> Please search for issues before creating new ones. Can do this for all your recent issues? I knew about all of them so they might very already exist somewhere. Include https://github.com/etalab/data.gouv.fr in your search.

sorry my bad again
