### ISSUE TITLE
Bug upload logo of an organisation

### ISSUE THREAD

**Issue by tportier** [opendatateam/udata#1145] opened 2017-09-19 12:32 UTC
## Detailed Description

It is no more possible to attached a logo to an organisation. See the screenshot attached.

## Your Environment

* Browser Name and version: Tested with chrome and firefox
![capture_udata_logo](https://user-images.githubusercontent.com/600210/30592512-556c33a6-9d47-11e7-8c1e-74212047a6b3.PNG)

**Comment by noirbizarre** [comment] 2017-09-25 14:57
Closing this as its a duplicate of #1130
(This has been fixed in #1133 and soon to be released in udata 1.1.7)

**Closed by noirbizarre** 2017-09-25 14:57 UTC
