### ISSUE TITLE
AttributeError: 'Organization' object has no attribute 'badge'

### ISSUE THREAD

**Issue by tboye** [opendatateam/udata#3197] opened 2024-11-17 14:03 UTC
After [this change](https://github.com/opendatateam/udata/pull/3155/files#diff-da2e07ff2c5e7a01cc03139038bdd40e90840c8c36d1db5fd515e823199ec10fR86) I'm getting `AttributeError: 'Organization' object has no attribute 'badge'` error when calling `badge_label()`.

## Detailed Description
I'm not sure about the motivation for this change and where `self.badge` is supposed to be set, but it seems that it's not set anywhere at the moment, thus the error.

## Possible Implementation
`self.badge` could be replaced with `self._fields["badges"].field.document_type` like in `add_badge()`.

## Your Environment
udata `v10.0.1`

**Comment by magopian** [comment] 2024-11-18 09:00
Ah, that's well spotted, and indeed the fix you propose is the correct one, thanks! I've created a PR to fix it, and added a test ;)

**Comment by magopian** [comment] 2024-11-18 10:27
And it's now fixed in https://github.com/opendatateam/udata/pull/3198, will be in production with the next release!

**Comment by magopian** [comment] 2024-11-18 10:27
Thanks for submitting this issue, and thanks for investigating and finding out the root cause <3

**Closed** 2024-11-18 10:26 UTC
Labels: bug
