### ISSUE TITLE
Erreur 400 Mauvaise requête / Error 400 bad request

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1127] opened 2017-09-12 08:57 UTC
Just Install udata and udata gouvfr using the links http://udata.readthedocs.io/en/stable/installation/#installation-for-production and  https://github.com/etalab/udata-gouvfr

if the site is in English everything works fine!

if we pass the site in French the menus data and organization returns the error message "Erreur 400 Mauvaise requête / Error 400 bad request"

Debian 8.8

See file

[error_400.docx](https://github.com/opendatateam/udata/files/1295320/error_400.docx)

Thank for your support

**Comment by abulte** [comment] 2017-09-14 13:26
Hi @damonzon33, I just tested on a fresh install of `udata` + `udata-gouvfr` (stable versions) and could not reproduce the problem. Do you have some error logs you can provide? Thanks.

**Comment by damonzon33** [comment] 2017-09-14 14:25
Hi,

Please add some Data and Organizations or Reuse and you will get tje error.

Another user @pdartois have the same problem

https://gitter.im/opendatateam/udata

Thanks

**Comment by abulte** [comment] 2017-09-14 14:50
I did add some data, still no luck. An error log would be a great help to help us pinpoint the problem.

**Comment by damonzon33** [comment] 2017-09-15 05:58
I set my nginx error lo tio debug and got

2017/09/15 07:46:12 [debug] 25011#0: *1 chain writer out: 0000000000000000
2017/09/15 07:46:12 [debug] 25011#0: *1 event timer add: 11: 60000:1505454432884
2017/09/15 07:46:12 [debug] 25011#0: *1 http finalize request: -4, "/fr/organizations/?" a:1, c:3
2017/09/15 07:46:12 [debug] 25011#0: *1 http request count:3 blk:0
2017/09/15 07:46:12 [debug] 25011#0: *1 http finalize request: -4, "/fr/organizations/?" a:1, c:2
2017/09/15 07:46:12 [debug] 25011#0: *1 http request count:2 blk:0
2017/09/15 07:46:12 [debug] 25011#0: *1 post event 0000000001705D70
2017/09/15 07:46:12 [debug] 25011#0: *1 delete posted event 0000000001705D70
2017/09/15 07:46:12 [debug] 25011#0: *1 http upstream request: "/fr/organizations/?"
2017/09/15 07:46:12 [debug] 25011#0: *1 http upstream dummy handler
2017/09/15 07:46:13 [debug] 25011#0: *1 post event 00000000016C6BD0
2017/09/15 07:46:13 [debug] 25011#0: *1 post event 0000000001705D70
2017/09/15 07:46:13 [debug] 25011#0: *1 delete posted event 0000000001705D70
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream request: "/fr/organizations/?"
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream dummy handler
2017/09/15 07:46:13 [debug] 25011#0: *1 delete posted event 00000000016C6BD0
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream request: "/fr/organizations/?"
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream process header
2017/09/15 07:46:13 [debug] 25011#0: *1 malloc: 00000000016ADDE0:4096
2017/09/15 07:46:13 [debug] 25011#0: *1 recv: fd:11 4096 of 4096
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi status 400 "400 BAD REQUEST"
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi header: "Content-Type: text/html; charset=utf-8"
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi header: "Content-Length: 30675"
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi header done
2017/09/15 07:46:13 [debug] 25011#0: *1 xslt filter header
2017/09/15 07:46:13 [debug] 25011#0: *1 HTTP/1.1 400 BAD REQUEST
Server: nginx/1.6.2
Date: Fri, 15 Sep 2017 05:46:13 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 30675
Connection: keep-alive

2017/09/15 07:46:13 [debug] 25011#0: *1 write new buf t:1 f:0 00000000016ADBE0, pos 00000000016ADBE0, size: 173 file: 0, size: 0
2017/09/15 07:46:13 [debug] 25011#0: *1 http write filter: l:0 f:0 s:173
2017/09/15 07:46:13 [debug] 25011#0: *1 http cacheable: 0
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream process upstream
2017/09/15 07:46:13 [debug] 25011#0: *1 pipe read upstream: 1
2017/09/15 07:46:13 [debug] 25011#0: *1 pipe preread: 4005
2017/09/15 07:46:13 [debug] 25011#0: *1 posix_memalign: 00000000016DA240:4096 @16
2017/09/15 07:46:13 [debug] 25011#0: *1 input buf #0
2017/09/15 07:46:13 [debug] 25011#0: *1 malloc: 00000000016DB250:4096

**Comment by damonzon33** [comment] 2017-09-15 06:01
I set my nginx error log to debug an got 

2017/09/15 07:46:12 [debug] 25011#0: *1 chain writer buf fl:0 s:1085
2017/09/15 07:46:12 [debug] 25011#0: *1 chain writer in: 00000000016ECC18
2017/09/15 07:46:12 [debug] 25011#0: *1 writev: 1085
2017/09/15 07:46:12 [debug] 25011#0: *1 chain writer out: 0000000000000000
2017/09/15 07:46:12 [debug] 25011#0: *1 event timer add: 11: 60000:1505454432884
2017/09/15 07:46:12 [debug] 25011#0: *1 http finalize request: -4, "/fr/organizations/?" a:1, c:3
2017/09/15 07:46:12 [debug] 25011#0: *1 http request count:3 blk:0
2017/09/15 07:46:12 [debug] 25011#0: *1 http finalize request: -4, "/fr/organizations/?" a:1, c:2
2017/09/15 07:46:12 [debug] 25011#0: *1 http request count:2 blk:0
2017/09/15 07:46:12 [debug] 25011#0: *1 post event 0000000001705D70
2017/09/15 07:46:12 [debug] 25011#0: *1 delete posted event 0000000001705D70
2017/09/15 07:46:12 [debug] 25011#0: *1 http upstream request: "/fr/organizations/?"
2017/09/15 07:46:12 [debug] 25011#0: *1 http upstream dummy handler
2017/09/15 07:46:13 [debug] 25011#0: *1 post event 00000000016C6BD0
2017/09/15 07:46:13 [debug] 25011#0: *1 post event 0000000001705D70
2017/09/15 07:46:13 [debug] 25011#0: *1 delete posted event 0000000001705D70
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream request: "/fr/organizations/?"
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream dummy handler
2017/09/15 07:46:13 [debug] 25011#0: *1 delete posted event 00000000016C6BD0
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream request: "/fr/organizations/?"
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream process header
2017/09/15 07:46:13 [debug] 25011#0: *1 malloc: 00000000016ADDE0:4096
2017/09/15 07:46:13 [debug] 25011#0: *1 recv: fd:11 4096 of 4096
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi status 400 "400 BAD REQUEST"
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi header: "Content-Type: text/html; charset=utf-8"
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi header: "Content-Length: 30675"
2017/09/15 07:46:13 [debug] 25011#0: *1 http uwsgi header done
2017/09/15 07:46:13 [debug] 25011#0: *1 xslt filter header
2017/09/15 07:46:13 [debug] 25011#0: *1 HTTP/1.1 400 BAD REQUEST
Server: nginx/1.6.2
Date: Fri, 15 Sep 2017 05:46:13 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 30675
Connection: keep-alive

2017/09/15 07:46:13 [debug] 25011#0: *1 write new buf t:1 f:0 00000000016ADBE0, pos 00000000016ADBE0, size: 173 file: 0, size: 0
2017/09/15 07:46:13 [debug] 25011#0: *1 http write filter: l:0 f:0 s:173
2017/09/15 07:46:13 [debug] 25011#0: *1 http cacheable: 0
2017/09/15 07:46:13 [debug] 25011#0: *1 http upstream process upstream
2017/09/15 07:46:13 [debug] 25011#0: *1 pipe read upstream: 1
2017/09/15 07:46:13 [debug] 25011#0: *1 pipe preread: 4005
2017/09/15 07:46:13 [debug] 25011#0: *1 posix_memalign: 00000000016DA240:4096 @16
2017/09/15 07:46:13 [debug] 25011#0: *1 input buf #0
2017/09/15 07:46:13 [debug] 25011#0: *1 malloc: 00000000016DB250:4096
2017/09/15 07:46:13 [debug] 25011#0: *1 readv: 1:4096
2017/09/15 07:46:13 [debug] 25011#0: *1 pipe recv chain: 4096
2017/09/15 07:46:13 [debug] 25011#0: *1 input buf #1
2017/09/15 07:46:13 [debug] 25011#0: *1 malloc: 00000000016DC260:4096
2017/09/15 07:46:13 [debug] 25011#0: *1 readv: 1:4096
2017/09/15 07:46:13 [debug] 25011#0: *1 pipe recv chain: 4096
2017/09/15 07:46:13 [debug] 25011#0: *1 input buf #2
2017/09/15 07:46:13 [debug] 25011#0: *1 malloc: 00000000016DD270:409

**Comment by abulte** [comment] 2017-09-15 06:57
Thanks! You may have some more details in uwsgi logs, typically a `udata-front.log` file under `/var/log/uwsgi`. 

Please check you're running the latest version of ˋudataˋ too, cf the last comment on gitter.

**Comment by damonzon33** [comment] 2017-09-18 07:17
Hello,

I already have the latest version.

udata 1.1.6
udata-gouvfr 1.1.2


1- I just installed on a VM again and after adding some data I get the same error message.
Perhaps a configuration problem. can you please share your nginx.conf and udata.cfg file? 



2- I remarked by searching on google that many people encounter this error message with Django.I tried some configuration  in nginx conf file now even when changing English or French the message appears.

3 - I also noticed that by putting Minist(è)re des arm(é)es with accents in site-ID I have error message below in udata-front.log.The message disappears when I remove the accents

[2017-09-14 09:07:05,949] ERROR in app: Exception on /api/1/metrics/Ministère des armées [GET]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1856, in process_response
    response = handler(response)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 221, in collect_stats
    'action_name': urllib.quote(action_name),
  File "/usr/lib/python2.7/urllib.py", line 1294, in quote

is there an encoding problem on my debian?

ci-dessous la commande locale

d.hanne@pod:~$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

thank for your support

**Comment by damonzon33** [comment] 2017-09-18 07:19
I tried to reindex/purge/clean, I clean redis cache without success

**Comment by damonzon33** [comment] 2017-09-18 07:19
I tried to reindex/purge/clean, I clean redis cache, nginx cache without success

**Comment by oncletom** [comment] 2017-09-18 07:35
@abulte I wonder if the problem is linked to the recent search issues, when organizations were displayed in facets but not yet indexed.

@damonzon33 I also wonder if the [**site-ID**](http://udata.readthedocs.io/en/stable/adapting-settings/#site_id) should be a string contained in this range `[a-Z0-9]`. Is it a different problem than the original one?

Also, could you list here the name of the organisations you added manually so as we could manage to reproduce the issue?

Thanks a bunch.

**Comment by damonzon33** [comment] 2017-09-18 08:07
@oncletom about site-ID   Is it a different problem than the original.

the problem bad request occurs on our server which is not connected on Internet. it is not only on the organization but also on datasets or reuse. see screenshot. Is the installation procedure correct? To reproduce the problem I just installed a VM by exactly following the document (same configuration file uwsgi, nginx) described on the site. After adding some data I get the error message
![image](https://user-images.githubusercontent.com/30826928/30533354-31d5db66-9c59-11e7-8837-ad39181297ed.png)

**Comment by oncletom** [comment] 2017-09-18 08:56
Thanks @damonzon33. Which version of ElasticSearch do you use out of curiosity?

**Comment by abulte** [comment] 2017-09-18 08:56
@oncletom nope, looks like #1008 indeed but: fixed in latest (just tested), error message is different and it would happen on all languages, only French.

**Comment by abulte** [comment] 2017-09-18 09:03
I'm gonna try to reproduce on a fresh Debian 8 machine.

**Comment by damonzon33** [comment] 2017-09-18 09:17
@oncletom 

root@udataVM:~# curl -XGET 'localhost:9200'
{
  "name" : "Gammenon the Gatherer",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "mHvcpq87ToyJkQFN5BFamw",
  "version" : {
    "number" : "2.4.6",
    "build_hash" : "5376dca9f70f3abef96a77f4bb22720ace8240fd",
    "build_timestamp" : "2017-07-18T12:17:44Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"

**Comment by abulte** [comment] 2017-09-18 11:32
@damonzon33 we managed to reproduce the issue. We'll keep you posted for a workaround/resolution.

**Comment by damonzon33** [comment] 2017-09-18 11:48
@abulte thank you!

**Comment by noirbizarre** [comment] 2017-09-26 15:46
This should be fixed by #1127

**Closed by noirbizarre** 2017-09-26 15:46 UTC
